id = "neo"
name = "Neo"
version = "0.0.1"
schema_version = 1
description = "Neo language support for Zed."
authors = ["Skyler Burwell"]
languages = ["languages/neo"]

[grammars.neo]
repository = "https://codeberg.org/neolang/tree-sitter-neo"
rev = "97b3c3552acbeb08b1dc5be41053ddccb0b2c40b"
